---
abstract: 'Interface to the Atomic Parsley command'
author:
  - 'Andrew Jones <andrew@arjones.co.uk>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AtomicParsley-Command
requires:
  File::Copy: 0
  File::Spec: 0
  IPC::Cmd: 0
  Object::Tiny: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrewrjones/perl5-AtomicParsley-Command/issues
  homepage: https://github.com/andrewrjones/perl5-AtomicParsley-Command
  repository: https://github.com/andrewrjones/perl5-AtomicParsley-Command.git
version: 1.130420
